#ifndef EXTENSIONS_H_
#define EXTENSIONS_H_

#include <stdint.h>

#define HASH_PRIME 4294947451
#define HASH_STR_QUAD(s) ((s)[0] | ((s)[0] ? (s)[1] | ((s)[1] ? (s)[2] | ((s)[2] ? (s)[3] : 0) << 8 : 0) << 8 : 0) << 8)

static inline uint32_t hash_str(char const *str)
{
	if(str[0] && str[1] && str[2] && str[3])
		return *(uint32_t *)str + HASH_PRIME * hash_str(str + 4);
	else
		return HASH_STR_QUAD(str);
}

#define H(a, b, c, d, prev) (((uint32_t)(a) | (uint32_t)(b) << 8 | (uint32_t)(c) << 16 | (uint32_t)(d) << 24) + HASH_PRIME * (prev))

static inline char const *mime_to_extension(char const *str)
{
	switch(hash_str(str))
	{
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('a','c','a','d',0)))):
			return ".dwg";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('a','r','j',0,0)))):
			return ".arj";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('b','a','s','e',H('6','4',0,0,0))))):
			return ".mm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('b','i','n','h',H('e','x',0,0,0))))):
			return ".hqx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('b','i','n','h',H('e','x','4',0,0))))):
			return ".hqx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('b','o','o','k',0)))):
			return ".book";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('c','d','f',0,0)))):
			return ".cdf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('c','l','a','r',H('i','s','c','a',H('d',0,0,0,0)))))):
			return ".ccad";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('c','o','m','m',H('o','n','g','r',H('o','u','n','d',0)))))):
			return ".dp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('d','r','a','f',H('t','i','n','g',0))))):
			return ".drw";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('d','s','p','t',H('y','p','e',0,0))))):
			return ".tsp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('d','x','f',0,0)))):
			return ".dxf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('e','c','m','a',H('s','c','r','i',H('p','t',0,0,0)))))):
			return ".js";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('e','n','v','o',H('y',0,0,0,0))))):
			return ".evy";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('e','x','c','e',H('l',0,0,0,0))))):
			return ".xls";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('f','r','a','c',H('t','a','l','s',0))))):
			return ".fif";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('f','r','e','e',H('l','o','a','d',H('e','r',0,0,0)))))):
			return ".frl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('f','u','t','u',H('r','e','s','p',H('l','a','s','h',0)))))):
			return ".spl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('g','n','u','t',H('a','r',0,0,0))))):
			return ".tgz";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('g','r','o','u',H('p','w','i','s',H('e',0,0,0,0)))))):
			return ".vew";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('h','l','p',0,0)))):
			return ".hlp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('h','t','a',0,0)))):
			return ".hta";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('i','-','d','e',H('a','s',0,0,0))))):
			return ".unv";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('i','g','e','s',0)))):
			return ".iges";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('i','n','f',0,0)))):
			return ".inf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('j','a','v','a',0)))):
			return ".class";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('j','a','v','a',H('-','b','y','t',H('e','-','c','o',H('d','e',0,0,0))))))):
			return ".class";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('j','a','v','a',H('s','c','r','i',H('p','t',0,0,0)))))):
			return ".js";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('l','h','a',0,0)))):
			return ".lha";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('l','z','x',0,0)))):
			return ".lzx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','a','c','-',H('b','i','n','a',H('r','y',0,0,0)))))):
			return ".bin";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','a','c','-',H('b','i','n','h',H('e','x',0,0,0)))))):
			return ".hqx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','a','c','-',H('b','i','n','h',H('e','x','4','0',0)))))):
			return ".hqx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','a','c','-',H('c','o','m','p',H('a','c','t','p',H('r','o',0,0,0))))))):
			return ".cpt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','a','c','b',H('i','n','a','r',H('y',0,0,0,0)))))):
			return ".bin";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','a','r','c',0)))):
			return ".mrc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','b','e','d',H('l','e','t',0,0))))):
			return ".mbd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','c','a','d',0)))):
			return ".mcd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','i','m','e',0)))):
			return ".aps";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','s','p','o',H('w','e','r','p',H('o','i','n','t',0)))))):
			return ".ppt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','s','w','o',H('r','d',0,0,0))))):
			return ".doc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('m','s','w','r',H('i','t','e',0,0))))):
			return ".wri";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('n','e','t','m',H('c',0,0,0,0))))):
			return ".mcp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('o','c','t','e',H('t','-','s','t',H('r','e','a','m',0)))))):
			return ".bin";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('o','d','a',0,0)))):
			return ".oda";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','d','f',0,0)))):
			return ".pdf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','c','s',H('-','1','2',0,0))))):
			return ".p12";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','c','s',H('-','c','r','l',0))))):
			return ".crl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','c','s',H('1','0',0,0,0))))):
			return ".p10";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','c','s',H('7','-','m','i',H('m','e',0,0,0)))))):
			return ".p7m";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','c','s',H('7','-','s','i',H('g','n','a','t',H('u','r','e',0,0))))))):
			return ".p7s";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','i','x',H('-','c','e','r',H('t',0,0,0,0)))))):
			return ".crt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','k','i','x',H('-','c','r','l',0))))):
			return ".crl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','l','a','i',H('n',0,0,0,0))))):
			return ".txt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','o','s','t',H('s','c','r','i',H('p','t',0,0,0)))))):
			return ".ps";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','o','w','e',H('r','p','o','i',H('n','t',0,0,0)))))):
			return ".ppt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('p','r','o','_',H('e','n','g',0,0))))):
			return ".part";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('r','i','n','g',H('i','n','g','-',H('t','o','n','e',H('s',0,0,0,0))))))):
			return ".rng";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('r','t','f',0,0)))):
			return ".rtf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','d','p',0,0)))):
			return ".sdp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','e','a',0,0)))):
			return ".sea";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','e','t',0,0)))):
			return ".set";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','l','a',0,0)))):
			return ".stl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','m','i','l',0)))):
			return ".smil";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','o','l','i',H('d','s',0,0,0))))):
			return ".sol";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','o','u','n',H('d','e','r',0,0))))):
			return ".sdr";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','t','e','p',0)))):
			return ".step";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('s','t','r','e',H('a','m','i','n',H('g','m','e','d',H('i','a',0,0,0))))))):
			return ".ssm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('t','o','o','l',H('b','o','o','k',0))))):
			return ".tbk";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','d','a',0,0)))):
			return ".vda";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('f','d','f',0,0))))):
			return ".fdf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('h','p','-','h',H('p','g','l',0,0)))))):
			return ".hpgl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('h','p','-','p',H('c','l',0,0,0)))))):
			return ".pcl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','e',H('x','c','e','l',0)))))):
			return ".xls";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','p',H('k','i','.','c',H('e','r','t','s',H('t','o','r','e',0)))))))):
			return ".sst";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','p',H('k','i','.','p',H('k','o',0,0,0))))))):
			return ".pko";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','p',H('k','i','.','s',H('e','c','c','a',H('t',0,0,0,0)))))))):
			return ".cat";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','p',H('k','i','.','s',H('t','l',0,0,0))))))):
			return ".stl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','p',H('o','w','e','r',H('p','o','i','n',H('t',0,0,0,0)))))))):
			return ".ppt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('m','s','-','p',H('r','o','j','e',H('c','t',0,0,0))))))):
			return ".mpp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('n','o','k','i',H('a','.','c','o',H('n','f','i','g',H('u','r','a','t',H('i','o','n','-',H('m','e','s','s',H('a','g','e',0,0))))))))))):
			return ".ncm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('n','o','k','i',H('a','.','r','i',H('n','g','i','n',H('g','-','t','o',H('n','e',0,0,0))))))))):
			return ".rng";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('r','n','-','r',H('e','a','l','m',H('e','d','i','a',0))))))):
			return ".rm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('r','n','-','r',H('e','a','l','p',H('l','a','y','e',H('r',0,0,0,0)))))))):
			return ".rnx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('w','a','p','.',H('w','m','l','c',0)))))):
			return ".wmlc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('w','a','p','.',H('w','m','l','s',H('c','r','i','p',H('t','c',0,0,0)))))))):
			return ".wmlsc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','n','d','.',H('x','a','r','a',0))))):
			return ".web";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','o','c','a',H('l','t','e','c',H('-','m','e','d',H('i','a','-','d',H('e','s','c',0,0)))))))):
			return ".vmd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('v','o','c','a',H('l','t','e','c',H('-','m','e','d',H('i','a','-','f',H('i','l','e',0,0)))))))):
			return ".vmf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('w','o','r','d',H('p','e','r','f',H('e','c','t',0,0)))))):
			return ".wp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('w','o','r','d',H('p','e','r','f',H('e','c','t','6',H('.','0',0,0,0))))))):
			return ".w60";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('w','o','r','d',H('p','e','r','f',H('e','c','t','6',H('.','1',0,0,0))))))):
			return ".w61";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','1','2',H('3',0,0,0,0))))):
			return ".wk1";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','a','i',H('m',0,0,0,0))))):
			return ".aim";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','a','u',H('t','h','o','r',H('w','a','r','e',H('-','b','i','n',0))))))):
			return ".aab";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','a','u',H('t','h','o','r',H('w','a','r','e',H('-','m','a','p',0))))))):
			return ".aam";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','a','u',H('t','h','o','r',H('w','a','r','e',H('-','s','e','g',0))))))):
			return ".aas";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','c',H('p','i','o',0,0))))):
			return ".bcpio";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','i',H('n','a','r','y',0))))):
			return ".bin";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','i',H('n','h','e','x',H('4','0',0,0,0)))))):
			return ".hqx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','s',H('h',0,0,0,0))))):
			return ".bsh";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','y',H('t','e','c','o',H('d','e','.','e',H('l','i','s','p',0))))))):
			return ".elc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','y',H('t','e','c','o',H('d','e','.','p',H('y','t','h','o',H('n',0,0,0,0)))))))):
			return ".pyc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','z',H('i','p',0,0,0))))):
			return ".bz";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','b','z',H('i','p','2',0,0))))):
			return ".bz2";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','d',H('f',0,0,0,0))))):
			return ".cdf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','d',H('l','i','n','k',0))))):
			return ".vcd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','h',H('a','t',0,0,0))))):
			return ".chat";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','m',H('u','-','r','a',H('s','t','e','r',0)))))):
			return ".ras";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','o',H('c','o','a',0,0))))):
			return ".cco";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','o',H('m','p','a','c',H('t','p','r','o',0)))))):
			return ".cpt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','o',H('m','p','r','e',H('s','s',0,0,0)))))):
			return ".z";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','o',H('m','p','r','e',H('s','s','e','d',0)))))):
			return ".gz";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','o',H('n','f','e','r',H('e','n','c','e',0)))))):
			return ".nsc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','p',H('i','o',0,0,0))))):
			return ".cpio";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','p',H('t',0,0,0,0))))):
			return ".cpt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','c','s',H('h',0,0,0,0))))):
			return ".csh";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','d','e',H('e','p','v',0,0))))):
			return ".deepv";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','d','i',H('r','e','c','t',H('o','r',0,0,0)))))):
			return ".dcr";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','d','v',H('i',0,0,0,0))))):
			return ".dvi";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','e','l',H('c',0,0,0,0))))):
			return ".elc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','e','n',H('v','o','y',0,0))))):
			return ".evy";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','e','s',H('r','e','h','b',H('e','r',0,0,0)))))):
			return ".es";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','e','x',H('c','e','l',0,0))))):
			return ".xls";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','e','x',H('e','c','u','t',H('a','b','l','e',0)))))):
			return ".bin";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','f','r',H('a','m','e',0,0))))):
			return ".mif";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','f','r',H('e','e','l','a',H('n','c','e',0,0)))))):
			return ".pre";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','g','s',H('p',0,0,0,0))))):
			return ".gsp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','g','s',H('s',0,0,0,0))))):
			return ".gss";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','g','t',H('a','r',0,0,0))))):
			return ".gtar";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','g','z',H('i','p',0,0,0))))):
			return ".gz";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','h','d',H('f',0,0,0,0))))):
			return ".hdf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','h','e',H('l','p','f','i',H('l','e',0,0,0)))))):
			return ".hlp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','h','t',H('t','p','d','-',H('i','m','a','p',0)))))):
			return ".imap";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','i','m',H('a',0,0,0,0))))):
			return ".ima";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','i','n',H('t','e','r','n',H('e','t','t','-',H('s','i','g','n',H('u','p',0,0,0)))))))):
			return ".ins";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','i','n',H('v','e','n','t',H('o','r',0,0,0)))))):
			return ".iv";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','i','p',H('2',0,0,0,0))))):
			return ".ip";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','j','a',H('v','a','-','c',H('l','a','s','s',0)))))):
			return ".class";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','j','a',H('v','a','-','c',H('o','m','m','e',H('r','c','e',0,0))))))):
			return ".jcm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','j','a',H('v','a','s','c',H('r','i','p','t',0)))))):
			return ".js";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','k','o',H('a','n',0,0,0))))):
			return ".skt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','k','s',H('h',0,0,0,0))))):
			return ".ksh";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','a',H('t','e','x',0,0))))):
			return ".latex";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','h',H('a',0,0,0,0))))):
			return ".lha";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','i',H('s','p',0,0,0))))):
			return ".lsp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','i',H('v','e','s','c',H('r','e','e','n',0)))))):
			return ".ivy";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','o',H('t','u','s',0,0))))):
			return ".wq1";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','o',H('t','u','s','s',H('c','r','e','e',H('n','c','a','m',0))))))):
			return ".scm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','z',H('h',0,0,0,0))))):
			return ".lzh";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','l','z',H('x',0,0,0,0))))):
			return ".lzx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','a',H('c','-','b','i',H('n','h','e','x',H('4','0',0,0,0))))))):
			return ".hqx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','a',H('c','b','i','n',H('a','r','y',0,0)))))):
			return ".bin";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','a',H('g','i','c','-',H('c','a','p','-',H('p','a','c','k',H('a','g','e','-',H('1','.','0',0,0))))))))):
			return ".mc$";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','a',H('t','h','c','a',H('d',0,0,0,0)))))):
			return ".mcd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','e',H('m','e',0,0,0))))):
			return ".mm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','i',H('d','i',0,0,0))))):
			return ".midi";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','i',H('f',0,0,0,0))))):
			return ".mif";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','i',H('x','-','t','r',H('a','n','s','f',H('e','r',0,0,0))))))):
			return ".nix";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','p',H('l','a','y','e',H('r','2',0,0,0)))))):
			return ".asx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','s',H('e','x','c','e',H('l',0,0,0,0)))))):
			return ".xls";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','m','s',H('p','o','w','e',H('r','p','o','i',H('n','t',0,0,0))))))):
			return ".ppt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','a',H('v','i','-','a',H('n','i','m','a',H('t','i','o','n',0))))))):
			return ".ani";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','a',H('v','i','d','o',H('c',0,0,0,0)))))):
			return ".nvd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','a',H('v','i','m','a',H('p',0,0,0,0)))))):
			return ".map";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','a',H('v','i','s','t',H('y','l','e',0,0)))))):
			return ".stl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','e',H('t','c','d','f',0))))):
			return ".cdf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','e',H('w','t','o','n',H('-','c','o','m',H('p','a','t','i',H('b','l','e','-',H('p','k','g',0,0))))))))):
			return ".pkg";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','n','o',H('k','i','a','-',H('9','0','0','0',H('-','c','o','m',H('m','u','n','i',H('c','a','t','o',H('r','-','a','d',H('d','-','o','n',H('-','s','o','f',H('t','w','a','r',H('e',0,0,0,0)))))))))))))):
			return ".aos";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','o','b',H('j','e','c','t',0))))):
			return ".o";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','o','m',H('c',0,0,0,0))))):
			return ".omc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','o','m',H('c','d','a','t',H('a','m','a','k',H('e','r',0,0,0))))))):
			return ".omcd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','o','m',H('c','r','e','g',H('e','r','a','t',H('o','r',0,0,0))))))):
			return ".omcr";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','a',H('g','e','m','a',H('k','e','r',0,0)))))):
			return ".pm5";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','c',H('l',0,0,0,0))))):
			return ".pcl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','i',H('x','c','l','s',H('c','r','i','p',H('t',0,0,0,0))))))):
			return ".plx";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','k',H('c','s','1','0',0))))):
			return ".p10";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','k',H('c','s','1','2',0))))):
			return ".p12";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','k',H('c','s','7','-',H('c','e','r','t',H('i','f','i','c',H('a','t','e','s',0)))))))):
			return ".spc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','k',H('c','s','7','-',H('c','e','r','t',H('r','e','q','r',H('e','s','p',0,0)))))))):
			return ".p7r";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','k',H('c','s','7','-',H('m','i','m','e',0)))))):
			return ".p7m";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','k',H('c','s','7','-',H('s','i','g','n',H('a','t','u','r',H('e',0,0,0,0)))))))):
			return ".p7a";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','o',H('i','n','t','p',H('l','u','s',0,0)))))):
			return ".css";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','o',H('r','t','a','b',H('l','e','-','a',H('n','y','m','a',H('p',0,0,0,0)))))))):
			return ".pnm";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','p','r',H('o','j','e','c',H('t',0,0,0,0)))))):
			return ".mpc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','q','p',H('r','o',0,0,0))))):
			return ".wb1";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','r','t',H('f',0,0,0,0))))):
			return ".rtf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','d',H('p',0,0,0,0))))):
			return ".sdp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','e',H('a',0,0,0,0))))):
			return ".sea";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','e',H('e','l','o','g',H('o',0,0,0,0)))))):
			return ".sl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','h',0)))):
			return ".sh";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','h',H('a','r',0,0,0))))):
			return ".shar";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','h',H('o','c','k','w',H('a','v','e','-',H('f','l','a','s',H('h',0,0,0,0)))))))):
			return ".swf";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','i',H('t',0,0,0,0))))):
			return ".sit";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','p',H('r','i','t','e',0))))):
			return ".sprite";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','t',H('u','f','f','i',H('t',0,0,0,0)))))):
			return ".sit";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','v',H('4','c','p','i',H('o',0,0,0,0)))))):
			return ".sv4cpio";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','s','v',H('4','c','r','c',0))))):
			return ".sv4crc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','a',H('r',0,0,0,0))))):
			return ".tar";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','b',H('o','o','k',0,0))))):
			return ".tbk";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','c',H('l',0,0,0,0))))):
			return ".tcl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','e',H('x',0,0,0,0))))):
			return ".tex";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','e',H('x','i','n','f',H('o',0,0,0,0)))))):
			return ".texi";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','r',H('o','f','f',0,0))))):
			return ".roff";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','r',H('o','f','f','-',H('m','a','n',0,0)))))):
			return ".man";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','r',H('o','f','f','-',H('m','e',0,0,0)))))):
			return ".me";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','r',H('o','f','f','-',H('m','s',0,0,0)))))):
			return ".ms";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','t','r',H('o','f','f','-',H('m','s','v','i',H('d','e','o',0,0))))))):
			return ".avi";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','u','s',H('t','a','r',0,0))))):
			return ".ustar";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','v','i',H('s','i','o',0,0))))):
			return ".vsd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','v','n',H('d','.','a','u',H('d','i','o','e',H('x','p','l','o',H('s','i','o','n',H('.','m','z','z',0))))))))):
			return ".mzz";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','v','n',H('d','.','l','s',H('-','x','p','i',H('x',0,0,0,0))))))):
			return ".xpix";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','v','r',H('m','l',0,0,0))))):
			return ".vrml";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','w','a',H('i','s','-','s',H('o','u','r','c',H('e',0,0,0,0))))))):
			return ".wsrc";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','w','i',H('n','h','e','l',H('p',0,0,0,0)))))):
			return ".hlp";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','w','i',H('n','t','a','l',H('k',0,0,0,0)))))):
			return ".wtk";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','w','o',H('r','l','d',0,0))))):
			return ".wrl";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','w','p',H('w','i','n',0,0))))):
			return ".wpd";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','w','r',H('i',0,0,0,0))))):
			return ".wri";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','x','5',H('0','9','-','c',H('a','-','c','e',H('r','t',0,0,0))))))):
			return ".crt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','x','5',H('0','9','-','u',H('s','e','r','-',H('c','e','r','t',0))))))):
			return ".crt";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','-','z','i',H('p','-','c','o',H('m','p','r','e',H('s','s','e','d',0))))))):
			return ".zip";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('x','m','l',0,0)))):
			return ".xml";
		case H('a','p','p','l',H('i','c','a','t',H('i','o','n','/',H('z','i','p',0,0)))):
			return ".zip";
		case H('a','u','d','i',H('o','/','a','i',H('f','f',0,0,0))):
			return ".aiff";
		case H('a','u','d','i',H('o','/','b','a',H('s','i','c',0,0))):
			return ".au";
		case H('a','u','d','i',H('o','/','i','t',0)):
			return ".it";
		case H('a','u','d','i',H('o','/','m','a',H('k','e',0,0,0))):
			return ".funk";
		case H('a','u','d','i',H('o','/','m','a',H('k','e','.','m',H('y','.','f','u',H('n','k',0,0,0))))):
			return ".pfunk";
		case H('a','u','d','i',H('o','/','m','i',H('d','i',0,0,0))):
			return ".midi";
		case H('a','u','d','i',H('o','/','m','o',H('d',0,0,0,0))):
			return ".mod";
		case H('a','u','d','i',H('o','/','m','p',H('e','g',0,0,0))):
			return ".mpg";
		case H('a','u','d','i',H('o','/','m','p',H('e','g','3',0,0))):
			return ".mp3";
		case H('a','u','d','i',H('o','/','n','s',H('p','a','u','d',H('i','o',0,0,0)))):
			return ".lma";
		case H('a','u','d','i',H('o','/','s','3',H('m',0,0,0,0))):
			return ".s3m";
		case H('a','u','d','i',H('o','/','t','s',H('p','-','a','u',H('d','i','o',0,0)))):
			return ".tsi";
		case H('a','u','d','i',H('o','/','t','s',H('p','l','a','y',H('e','r',0,0,0)))):
			return ".tsp";
		case H('a','u','d','i',H('o','/','v','n',H('d','.','q','c',H('e','l','p',0,0)))):
			return ".qcp";
		case H('a','u','d','i',H('o','/','v','o',H('c',0,0,0,0))):
			return ".voc";
		case H('a','u','d','i',H('o','/','v','o',H('x','w','a','r',H('e',0,0,0,0)))):
			return ".vox";
		case H('a','u','d','i',H('o','/','w','a',H('v',0,0,0,0))):
			return ".wav";
		case H('a','u','d','i',H('o','/','x','-',H('a','d','p','c',H('m',0,0,0,0)))):
			return ".snd";
		case H('a','u','d','i',H('o','/','x','-',H('a','i','f','f',0))):
			return ".aiff";
		case H('a','u','d','i',H('o','/','x','-',H('a','u',0,0,0))):
			return ".au";
		case H('a','u','d','i',H('o','/','x','-',H('g','s','m',0,0))):
			return ".gsm";
		case H('a','u','d','i',H('o','/','x','-',H('j','a','m',0,0))):
			return ".jam";
		case H('a','u','d','i',H('o','/','x','-',H('l','i','v','e',H('a','u','d','i',H('o',0,0,0,0))))):
			return ".lam";
		case H('a','u','d','i',H('o','/','x','-',H('m','i','d',0,0))):
			return ".midi";
		case H('a','u','d','i',H('o','/','x','-',H('m','i','d','i',0))):
			return ".midi";
		case H('a','u','d','i',H('o','/','x','-',H('m','o','d',0,0))):
			return ".mod";
		case H('a','u','d','i',H('o','/','x','-',H('m','p','e','g',0))):
			return ".mp2";
		case H('a','u','d','i',H('o','/','x','-',H('m','p','e','g',H('-','3',0,0,0)))):
			return ".mp3";
		case H('a','u','d','i',H('o','/','x','-',H('m','p','e','q',H('u','r','l',0,0)))):
			return ".m3u";
		case H('a','u','d','i',H('o','/','x','-',H('n','s','p','a',H('u','d','i','o',0)))):
			return ".lma";
		case H('a','u','d','i',H('o','/','x','-',H('p','n','-','r',H('e','a','l','a',H('u','d','i','o',0))))):
			return ".ra";
		case H('a','u','d','i',H('o','/','x','-',H('p','n','-','r',H('e','a','l','a',H('u','d','i','o',H('-','p','l','u',H('g','i','n',0,0))))))):
			return ".rmp";
		case H('a','u','d','i',H('o','/','x','-',H('p','s','i','d',0))):
			return ".sid";
		case H('a','u','d','i',H('o','/','x','-',H('r','e','a','l',H('a','u','d','i',H('o',0,0,0,0))))):
			return ".ra";
		case H('a','u','d','i',H('o','/','x','-',H('t','w','i','n',H('v','q',0,0,0)))):
			return ".vqf";
		case H('a','u','d','i',H('o','/','x','-',H('t','w','i','n',H('v','q','-','p',H('l','u','g','i',H('n',0,0,0,0)))))):
			return ".vql";
		case H('a','u','d','i',H('o','/','x','-',H('v','n','d','.',H('a','u','d','i',H('o','e','x','p',H('l','o','s','i',H('o','n','.','m',H('j','u','i','c',H('e','m','e','d',H('i','a','f','i',H('l','e',0,0,0))))))))))):
			return ".mjf";
		case H('a','u','d','i',H('o','/','x','-',H('v','o','c',0,0))):
			return ".voc";
		case H('a','u','d','i',H('o','/','x','-',H('w','a','v',0,0))):
			return ".wav";
		case H('a','u','d','i',H('o','/','x','m',0)):
			return ".xm";
		case H('c','h','e','m',H('i','c','a','l',H('/','x','-','p',H('d','b',0,0,0)))):
			return ".pdb";
		case H('d','r','a','w',H('i','n','g','/',H('x','-','d','w',H('f',0,0,0,0)))):
			return ".dwf";
		case H('i','-','w','o',H('r','l','d','/',H('i','-','v','r',H('m','l',0,0,0)))):
			return ".ivr";
		case H('i','m','a','g',H('e','/','b','m',H('p',0,0,0,0))):
			return ".bmp";
		case H('i','m','a','g',H('e','/','c','m',H('u','-','r','a',H('s','t','e','r',0)))):
			return ".rast";
		case H('i','m','a','g',H('e','/','f','i',H('f',0,0,0,0))):
			return ".fif";
		case H('i','m','a','g',H('e','/','f','l',H('o','r','i','a',H('n',0,0,0,0)))):
			return ".flo";
		case H('i','m','a','g',H('e','/','g','3',H('f','a','x',0,0))):
			return ".g3";
		case H('i','m','a','g',H('e','/','g','i',H('f',0,0,0,0))):
			return ".gif";
		case H('i','m','a','g',H('e','/','i','e',H('f',0,0,0,0))):
			return ".ief";
		case H('i','m','a','g',H('e','/','j','p',H('e','g',0,0,0))):
			return ".jpg";
		case H('i','m','a','g',H('e','/','j','u',H('t','v','i','s',H('i','o','n',0,0)))):
			return ".jut";
		case H('i','m','a','g',H('e','/','n','a',H('p','l','p','s',0))):
			return ".naplps";
		case H('i','m','a','g',H('e','/','p','i',H('c','t',0,0,0))):
			return ".pict";
		case H('i','m','a','g',H('e','/','p','j',H('p','e','g',0,0))):
			return ".jpg";
		case H('i','m','a','g',H('e','/','p','n',H('g',0,0,0,0))):
			return ".png";
		case H('i','m','a','g',H('e','/','t','i',H('f','f',0,0,0))):
			return ".tiff";
		case H('i','m','a','g',H('e','/','v','a',H('s','a',0,0,0))):
			return ".mcf";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','d','w',H('g',0,0,0,0)))):
			return ".dwg";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','f','p',H('x',0,0,0,0)))):
			return ".fpx";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','n','e',H('t','-','f','p',H('x',0,0,0,0))))):
			return ".fpx";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','r','n',H('-','r','e','a',H('l','f','l','a',H('s','h',0,0,0)))))):
			return ".rf";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','r','n',H('-','r','e','a',H('l','p','i','x',0))))):
			return ".rp";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','w','a',H('p','.','w','b',H('m','p',0,0,0))))):
			return ".wbmp";
		case H('i','m','a','g',H('e','/','v','n',H('d','.','x','i',H('f','f',0,0,0)))):
			return ".xif";
		case H('i','m','a','g',H('e','/','x','-',H('c','m','u','-',H('r','a','s','t',H('e','r',0,0,0))))):
			return ".ras";
		case H('i','m','a','g',H('e','/','x','-',H('d','w','g',0,0))):
			return ".dwg";
		case H('i','m','a','g',H('e','/','x','-',H('i','c','o','n',0))):
			return ".ico";
		case H('i','m','a','g',H('e','/','x','-',H('j','g',0,0,0))):
			return ".art";
		case H('i','m','a','g',H('e','/','x','-',H('j','p','s',0,0))):
			return ".jps";
		case H('i','m','a','g',H('e','/','x','-',H('n','i','f','f',0))):
			return ".niff";
		case H('i','m','a','g',H('e','/','x','-',H('p','c','x',0,0))):
			return ".pcx";
		case H('i','m','a','g',H('e','/','x','-',H('p','i','c','t',0))):
			return ".pct";
		case H('i','m','a','g',H('e','/','x','-',H('p','o','r','t',H('a','b','l','e',H('-','a','n','y',H('m','a','p',0,0)))))):
			return ".pnm";
		case H('i','m','a','g',H('e','/','x','-',H('p','o','r','t',H('a','b','l','e',H('-','b','i','t',H('m','a','p',0,0)))))):
			return ".pbm";
		case H('i','m','a','g',H('e','/','x','-',H('p','o','r','t',H('a','b','l','e',H('-','g','r','a',H('y','m','a','p',0)))))):
			return ".pgm";
		case H('i','m','a','g',H('e','/','x','-',H('p','o','r','t',H('a','b','l','e',H('-','g','r','e',H('y','m','a','p',0)))))):
			return ".pgm";
		case H('i','m','a','g',H('e','/','x','-',H('p','o','r','t',H('a','b','l','e',H('-','p','i','x',H('m','a','p',0,0)))))):
			return ".ppm";
		case H('i','m','a','g',H('e','/','x','-',H('q','u','i','c',H('k','t','i','m',H('e',0,0,0,0))))):
			return ".qif";
		case H('i','m','a','g',H('e','/','x','-',H('r','g','b',0,0))):
			return ".rgb";
		case H('i','m','a','g',H('e','/','x','-',H('t','i','f','f',0))):
			return ".tiff";
		case H('i','m','a','g',H('e','/','x','-',H('w','i','n','d',H('o','w','s','-',H('b','m','p',0,0))))):
			return ".bmp";
		case H('i','m','a','g',H('e','/','x','-',H('x','b','i','t',H('m','a','p',0,0)))):
			return ".xbm";
		case H('i','m','a','g',H('e','/','x','-',H('x','b','m',0,0))):
			return ".xbm";
		case H('i','m','a','g',H('e','/','x','-',H('x','p','i','x',H('m','a','p',0,0)))):
			return ".xpm";
		case H('i','m','a','g',H('e','/','x','-',H('x','w','d',0,0))):
			return ".xwd";
		case H('i','m','a','g',H('e','/','x','-',H('x','w','i','n',H('d','o','w','d',H('u','m','p',0,0))))):
			return ".xwd";
		case H('i','m','a','g',H('e','/','x','b',H('m',0,0,0,0))):
			return ".xbm";
		case H('i','m','a','g',H('e','/','x','p',H('m',0,0,0,0))):
			return ".xpm";
		case H('m','e','s','s',H('a','g','e','/',H('r','f','c','8',H('2','2',0,0,0)))):
			return ".mhtml";
		case H('m','o','d','e',H('l','/','i','g',H('e','s',0,0,0))):
			return ".iges";
		case H('m','o','d','e',H('l','/','v','n',H('d','.','d','w',H('f',0,0,0,0)))):
			return ".dwf";
		case H('m','o','d','e',H('l','/','v','r',H('m','l',0,0,0))):
			return ".vrml";
		case H('m','o','d','e',H('l','/','x','-',H('p','o','v',0,0))):
			return ".pov";
		case H('m','u','l','t',H('i','p','a','r',H('t','/','x','-',H('g','z','i','p',0)))):
			return ".gzip";
		case H('m','u','l','t',H('i','p','a','r',H('t','/','x','-',H('u','s','t','a',H('r',0,0,0,0))))):
			return ".ustar";
		case H('m','u','l','t',H('i','p','a','r',H('t','/','x','-',H('z','i','p',0,0)))):
			return ".zip";
		case H('m','u','s','i',H('c','/','c','r',H('e','s','c','e',H('n','d','o',0,0)))):
			return ".midi";
		case H('m','u','s','i',H('c','/','x','-',H('k','a','r','a',H('o','k','e',0,0)))):
			return ".kar";
		case H('p','a','l','e',H('o','v','u','/',H('x','-','p','v',0))):
			return ".pvu";
		case H('t','e','x','t',H('/','a','s','p',0)):
			return ".asp";
		case H('t','e','x','t',H('/','x','-','c',H('+','+',0,0,0))):
			return ".cpp";
		case H('t','e','x','t',H('/','c','s','s',0)):
			return ".css";
		case H('t','e','x','t',H('/','e','c','m',H('a','s','c','r',H('i','p','t',0,0)))):
			return ".js";
		case H('t','e','x','t',H('/','h','t','m',H('l',0,0,0,0))):
			return ".html";
		case H('t','e','x','t',H('/','j','a','v',H('a','s','c','r',H('i','p','t',0,0)))):
			return ".js";
		case H('t','e','x','t',H('/','m','c','f',0)):
			return ".mcf";
		case H('t','e','x','t',H('/','p','a','s',H('c','a','l',0,0))):
			return ".pas";
		case H('t','e','x','t',H('/','p','l','a',H('i','n',0,0,0))):
			return ".txt";
		case H('t','e','x','t',H('/','r','i','c',H('h','t','e','x',H('t',0,0,0,0)))):
			return ".rtf";
		case H('t','e','x','t',H('/','s','c','r',H('i','p','l','e',H('t',0,0,0,0)))):
			return ".wsc";
		case H('t','e','x','t',H('/','s','g','m',H('l',0,0,0,0))):
			return ".sgml";
		case H('t','e','x','t',H('/','t','a','b',H('-','s','e','p',H('a','r','a','t',H('e','d','-','v',H('a','l','u','e',H('s',0,0,0,0))))))):
			return ".tsv";
		case H('t','e','x','t',H('/','u','r','i',H('-','l','i','s',H('t',0,0,0,0)))):
			return ".uris";
		case H('t','e','x','t',H('/','v','n','d',H('.','a','b','c',0))):
			return ".abc";
		case H('t','e','x','t',H('/','v','n','d',H('.','f','m','i',H('.','f','l','e',H('x','s','t','o',H('r',0,0,0,0)))))):
			return ".flx";
		case H('t','e','x','t',H('/','v','n','d',H('.','r','n','-',H('r','e','a','l',H('t','e','x','t',0))))):
			return ".rt";
		case H('t','e','x','t',H('/','v','n','d',H('.','w','a','p',H('.','w','m','l',0)))):
			return ".wml";
		case H('t','e','x','t',H('/','v','n','d',H('.','w','a','p',H('.','w','m','l',H('s','c','r','i',H('p','t',0,0,0)))))):
			return ".wmls";
		case H('t','e','x','t',H('/','w','e','b',H('v','i','e','w',H('h','t','m','l',0)))):
			return ".htt";
		case H('t','e','x','t',H('/','x','-','a',H('s','m',0,0,0))):
			return ".asm";
		case H('t','e','x','t',H('/','x','-','a',H('u','d','i','o',H('s','o','f','t',H('-','i','n','t',H('r','a',0,0,0)))))):
			return ".aip";
		case H('t','e','x','t',H('/','x','-','c',0)):
			return ".c";
		case H('t','e','x','t',H('/','x','-','c',H('o','m','p','o',H('n','e','n','t',0)))):
			return ".htc";
		case H('t','e','x','t',H('/','x','-','f',H('o','r','t','r',H('a','n',0,0,0)))):
			return ".f77";
		case H('t','e','x','t',H('/','x','-','h',0)):
			return ".h";
		case H('t','e','x','t',H('/','x','-','j',H('a','v','a','-',H('s','o','u','r',H('c','e',0,0,0))))):
			return ".java";
		case H('t','e','x','t',H('/','x','-','l',H('a','-','a','s',H('f',0,0,0,0)))):
			return ".lsx";
		case H('t','e','x','t',H('/','x','-','m',0)):
			return ".m";
		case H('t','e','x','t',H('/','x','-','p',H('a','s','c','a',H('l',0,0,0,0)))):
			return ".p";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t',0,0,0,0)))):
			return ".hlb";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','c','s',H('h',0,0,0,0))))):
			return ".csh";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','e','l',H('i','s','p',0,0))))):
			return ".el";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','g','u',H('i','l','e',0,0))))):
			return ".scm";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','k','s',H('h',0,0,0,0))))):
			return ".ksh";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','l','i',H('s','p',0,0,0))))):
			return ".lsp";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','p','e',H('r','l',0,0,0))))):
			return ".pl";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','p','e',H('r','l','-','m',H('o','d','u','l',H('e',0,0,0,0))))))):
			return ".pm";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','p','h',H('y','t','o','n',0))))):
			return ".py";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','r','e',H('x','x',0,0,0))))):
			return ".rexx";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','s','c',H('h','e','m','e',0))))):
			return ".scm";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','s','h',0)))):
			return ".sh";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','t','c',H('l',0,0,0,0))))):
			return ".tcl";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','t','c',H('s','h',0,0,0))))):
			return ".tcsh";
		case H('t','e','x','t',H('/','x','-','s',H('c','r','i','p',H('t','.','z','s',H('h',0,0,0,0))))):
			return ".zsh";
		case H('t','e','x','t',H('/','x','-','s',H('e','r','v','e',H('r','-','p','a',H('r','s','e','d',H('-','h','t','m',H('l',0,0,0,0))))))):
			return ".ssi";
		case H('t','e','x','t',H('/','x','-','s',H('e','t','e','x',H('t',0,0,0,0)))):
			return ".etx";
		case H('t','e','x','t',H('/','x','-','s',H('g','m','l',0,0))):
			return ".sgml";
		case H('t','e','x','t',H('/','x','-','s',H('p','e','e','c',H('h',0,0,0,0)))):
			return ".spc";
		case H('t','e','x','t',H('/','x','-','u',H('i','l',0,0,0))):
			return ".uil";
		case H('t','e','x','t',H('/','x','-','u',H('u','e','n','c',H('o','d','e',0,0)))):
			return ".uue";
		case H('t','e','x','t',H('/','x','-','v',H('c','a','l','e',H('n','d','a','r',0)))):
			return ".vcs";
		case H('t','e','x','t',H('/','x','m','l',0)):
			return ".xml";
		case H('v','i','d','e',H('o','/','a','n',H('i','m','a','f',H('l','e','x',0,0)))):
			return ".afl";
		case H('v','i','d','e',H('o','/','a','v',H('i',0,0,0,0))):
			return ".avi";
		case H('v','i','d','e',H('o','/','a','v',H('s','-','v','i',H('d','e','o',0,0)))):
			return ".avs";
		case H('v','i','d','e',H('o','/','d','l',0)):
			return ".dl";
		case H('v','i','d','e',H('o','/','f','l',H('i',0,0,0,0))):
			return ".fli";
		case H('v','i','d','e',H('o','/','g','l',0)):
			return ".gl";
		case H('v','i','d','e',H('o','/','m','p',H('e','g',0,0,0))):
			return ".mpg";
		case H('v','i','d','e',H('o','/','m','s',H('v','i','d','e',H('o',0,0,0,0)))):
			return ".avi";
		case H('v','i','d','e',H('o','/','q','u',H('i','c','k','t',H('i','m','e',0,0)))):
			return ".mov";
		case H('v','i','d','e',H('o','/','v','d',H('o',0,0,0,0))):
			return ".vdo";
		case H('v','i','d','e',H('o','/','v','i',H('v','o',0,0,0))):
			return ".vivo";
		case H('v','i','d','e',H('o','/','v','n',H('d','.','r','n',H('-','r','e','a',H('l','v','i','d',H('e','o',0,0,0)))))):
			return ".rv";
		case H('v','i','d','e',H('o','/','v','n',H('d','.','v','i',H('v','o',0,0,0)))):
			return ".vivo";
		case H('v','i','d','e',H('o','/','v','o',H('s','a','i','c',0))):
			return ".vos";
		case H('v','i','d','e',H('o','/','w','e',H('b','m',0,0,0))):
			return ".webm";
		case H('v','i','d','e',H('o','/','x','-',H('a','m','t','-',H('d','e','m','o',H('r','u','n',0,0))))):
			return ".xdr";
		case H('v','i','d','e',H('o','/','x','-',H('a','m','t','-',H('s','h','o','w',H('r','u','n',0,0))))):
			return ".xsr";
		case H('v','i','d','e',H('o','/','x','-',H('a','t','o','m',H('i','c','3','d',H('-','f','e','a',H('t','u','r','e',0)))))):
			return ".fmf";
		case H('v','i','d','e',H('o','/','x','-',H('d','l',0,0,0))):
			return ".dl";
		case H('v','i','d','e',H('o','/','x','-',H('d','v',0,0,0))):
			return ".dv";
		case H('v','i','d','e',H('o','/','x','-',H('f','l','i',0,0))):
			return ".fli";
		case H('v','i','d','e',H('o','/','x','-',H('g','l',0,0,0))):
			return ".gl";
		case H('v','i','d','e',H('o','/','x','-',H('i','s','v','i',H('d','e','o',0,0)))):
			return ".isu";
		case H('v','i','d','e',H('o','/','x','-',H('m','o','t','i',H('o','n','-','j',H('p','e','g',0,0))))):
			return ".mjpg";
		case H('v','i','d','e',H('o','/','x','-',H('m','p','e','g',0))):
			return ".mp3";
		case H('v','i','d','e',H('o','/','x','-',H('m','p','e','q',H('2','a',0,0,0)))):
			return ".mp2";
		case H('v','i','d','e',H('o','/','x','-',H('m','s','-','a',H('s','f',0,0,0)))):
			return ".asf";
		case H('v','i','d','e',H('o','/','x','-',H('m','s','-','a',H('s','f','-','p',H('l','u','g','i',H('n',0,0,0,0)))))):
			return ".asx";
		case H('v','i','d','e',H('o','/','x','-',H('m','s','v','i',H('d','e','o',0,0)))):
			return ".avi";
		case H('v','i','d','e',H('o','/','x','-',H('q','t','c',0,0))):
			return ".qtc";
		case H('v','i','d','e',H('o','/','x','-',H('s','c','m',0,0))):
			return ".scm";
		case H('v','i','d','e',H('o','/','x','-',H('s','g','i','-',H('m','o','v','i',H('e',0,0,0,0))))):
			return ".mv";
		case H('w','i','n','d',H('o','w','s','/',H('m','e','t','a',H('f','i','l','e',0)))):
			return ".wmf";
		case H('w','w','w','/',H('m','i','m','e',0)):
			return ".mime";
		case H('x','-','c','o',H('n','f','e','r',H('e','n','c','e',H('/','x','-','c',H('o','o','l','t',H('a','l','k',0,0)))))):
			return ".ice";
		case H('x','-','m','u',H('s','i','c','/',H('x','-','m','i',H('d','i',0,0,0)))):
			return ".midi";
		case H('x','-','w','o',H('r','l','d','/',H('x','-','3','d',H('m','f',0,0,0)))):
			return ".3dmf";
		case H('x','-','w','o',H('r','l','d','/',H('x','-','s','v',H('r',0,0,0,0)))):
			return ".svr";
		case H('x','-','w','o',H('r','l','d','/',H('x','-','v','r',H('m','l',0,0,0)))):
			return ".vrml";
		case H('x','-','w','o',H('r','l','d','/',H('x','-','v','r',H('t',0,0,0,0)))):
			return ".vrt";
		case H('x','g','l','/',H('d','r','a','w',H('i','n','g',0,0))):
			return ".xgz";
		case H('x','g','l','/',H('m','o','v','i',H('e',0,0,0,0))):
			return ".xmz";
		default:
			return NULL;
	}
}

#endif
